/**
 * CodeLens — AI Analyzer Engine
 * Processes scanned project data into rich insights, summaries, and documentation.
 * Generates Mermaid.js architecture diagrams, API docs, and structured reports.
 */

function generateProjectInsights(project) {
  const { langCounts, totalFiles, totalLines, declarations, dependencies } = project;
  
  // Language breakdown
  const languages = Object.entries(langCounts)
    .sort((a, b) => b[1] - a[1])
    .map(([name, count]) => ({ name, count, percentage: Math.round(count / totalFiles * 100) }));

  // Primary language detection
  const primaryLang = languages[0]?.name || 'Unknown';

  // Project type detection
  let projectType = 'General';
  const hasPkg = dependencies.package;
  const hasReq = dependencies.python;
  const hasGo = dependencies.go;

  if (hasPkg) {
    const deps = Object.keys(hasPkg.deps || {});
    if (deps.includes('react') || deps.includes('vue') || deps.includes('angular')) projectType = 'Web Frontend';
    else if (deps.includes('express') || deps.includes('koa') || deps.includes('next')) projectType = 'Web Backend';
    else if (deps.includes('electron')) projectType = 'Desktop App';
    else if (deps.includes('react-native')) projectType = 'Mobile App';
    else projectType = 'Node.js Application';
  } else if (hasReq) {
    if (hasReq.some(d => d.includes('django') || d.includes('flask'))) projectType = 'Web Backend (Python)';
    else if (hasReq.some(d => d.includes('torch') || d.includes('tensorflow'))) projectType = 'ML/AI Project';
    else projectType = 'Python Application';
  } else if (hasGo) {
    projectType = 'Go Application';
  }

  // Complexity metrics
  const declTypes = {};
  declarations.forEach(d => {
    declTypes[d.type] = (declTypes[d.type] || 0) + 1;
  });

  const fileSizes = project.entries
    .filter(e => e.type === 'file' && e.lines > 0)
    .map(e => e.lines);
  
  const avgFileSize = fileSizes.length > 0 
    ? Math.round(fileSizes.reduce((a, b) => a + b, 0) / fileSizes.length)
    : 0;

  // Module identification (top-level directories)
  const modules = project.entries
    .filter(e => e.type === 'directory')
    .map(d => ({
      name: d.name,
      files: d.fileCount,
      lines: d.lineCount
    }));

  return {
    projectType,
    primaryLanguage: primaryLang,
    languages,
    modules,
    complexity: {
      totalDeclarations: declarations.length,
      functions: declTypes.function || 0,
      classes: declTypes.class || 0,
      avgFileSize,
      commentRatio: '—'
    },
    dependencies: {
      hasPackageJson: !!dependencies.package,
      hasRequirements: !!dependencies.python,
      hasGoMod: !!dependencies.go,
      packages: dependencies.package?.deps
        ? Object.entries(dependencies.package.deps)
            .sort((a, b) => b[1].length - a[1].length)
            .slice(0, 15)
            .map(([name, ver]) => ({ name, version: ver.replace('^', '') }))
        : [],
      pythonDeps: dependencies.python || [],
      goDeps: dependencies.go || []
    }
  };
}

/**
 * Generate a Mermaid.js architecture diagram from project structure.
 */
function generateArchitectureDiagram(project, insights) {
  const modules = insights.modules;

  if (modules.length === 0) {
    return `flowchart LR
  A[${project.projectName}] --> B[Source Files: ${project.totalFiles}]
  A --> C[Lines of Code: ${project.totalLines}]
  B --> D[Primary: ${insights.primaryLanguage}]
  style A fill:#7c5cfc,stroke:#333,stroke-width:2px,color:#fff
  style B fill:#1a1a24,stroke:#7c5cfc,color:#e4e4f0
  style C fill:#1a1a24,stroke:#7c5cfc,color:#e4e4f0
  style D fill:#1a1a24,stroke:#7c5cfc,color:#e4e4f0`;
  }

  const lines = ['flowchart TB'];

  // Root node
  lines.push(`  root[${project.projectName}]`);
  lines.push(`  style root fill:#7c5cfc,stroke:#333,stroke-width:3px,color:#fff,padding:10px`);

  modules.forEach((mod, i) => {
    lines.push(`  mod${i}[${mod.name}\\n${mod.files} files, ${mod.lines} lines]`);
    lines.push(`  root --> mod${i}`);
    lines.push(`  style mod${i} fill:#1a1a24,stroke:#7c5cfc,color:#e4e4f0`);
  });

  // Language info
  const langs = insights.languages.slice(0, 5);
  langs.forEach((l, i) => {
    const id = `lang${i}`;
    lines.push(`  ${id}[${l.name}: ${l.count} files]`);
    if (i === 0) lines.push(`  root -.-> ${id}`);
    lines.push(`  style ${id} fill:#24243a,stroke:#34d399,color:#e4e4f0`);
  });

  return lines.join('\n');
}

/**
 * Generate a complete README-like documentation markdown.
 */
function generateFullDocs(project, insights) {
  const { dependencies } = insights;
  
  let md = `# ${project.projectName}

> **Auto-generated by CodeLens** — AI-powered codebase intelligence

## 📊 Project Overview

| Metric | Value |
|:-------|:-----:|
| **Project Type** | ${insights.projectType} |
| **Primary Language** | ${insights.primaryLanguage} |
| **Total Files** | ${project.totalFiles} |
| **Total Lines of Code** | ${project.totalLines.toLocaleString()} |
| **Scan Duration** | ${project.scanTimeMs}ms |

## 🗂️ Language Breakdown

| Language | Files | % |
|:---------|:----:|:-:|
`;

  insights.languages.forEach(l => {
    md += `| ${l.name} | ${l.count} | ${l.percentage}% |\n`;
  });

  md += `\n## 🔬 Code Analysis\n\n`;
  md += `- **Functions/Methods**: ${insights.complexity.functions}\n`;
  md += `- **Classes**: ${insights.complexity.classes}\n`;
  md += `- **Average File Size**: ${insights.complexity.avgFileSize} lines\n`;

  if (insights.modules.length > 0) {
    md += `\n## 🏗️ Module Architecture\n\n`;
    md += `| Module | Files | Lines |\n|:-------|:----:|:----:|\n`;
    insights.modules.forEach(m => {
      md += `| ${m.name} | ${m.files} | ${m.lines.toLocaleString()} |\n`;
    });
    md += `\n### Architecture Diagram\n\n\`\`\`mermaid\n${generateArchitectureDiagram(project, insights)}\n\`\`\`\n`;
  }

  if (dependencies.packages.length > 0 || dependencies.pythonDeps.length > 0) {
    md += `\n## 📦 Dependencies\n\n`;
    if (dependencies.packages.length > 0) {
      md += `### Node.js Packages\n\n| Package | Version |\n|:--------|:-------:|\n`;
      dependencies.packages.slice(0, 20).forEach(p => {
        md += `| ${p.name} | ${p.version} |\n`;
      });
    }
    if (dependencies.pythonDeps.length > 0) {
      md += `\n### Python Dependencies\n\n\`\`\`\n${dependencies.pythonDeps.join('\n')}\n\`\`\`\n`;
    }
  }

  // File tree section
  md += `\n## 📁 File Tree\n\n\`\`\`\n`;
  md += buildFileTree(project.entries, project.projectName);
  md += `\`\`\`\n\n`;

  // Key declarations
  const keyDecls = project.declarations.slice(0, 30);
  if (keyDecls.length > 0) {
    md += `\n## 🔑 Key Definitions\n\n| Type | Name | File |\n|:---|:-----|:----|\n`;
    keyDecls.forEach(d => {
      md += `| ${d.type} | \`${d.name}\` | ${d.file} |\n`;
    });
  }

  md += `\n---\n\n> Generated by [CodeLens](https://github.com/user/codelens) — AI-powered codebase intelligence\n`;
  
  return md;
}

/**
 * Build a compact ASCII file tree.
 */
function buildFileTree(entries, rootName, prefix = '') {
  let tree = `${rootName}/\n`;
  
  const dirs = entries.filter(e => e.type === 'directory');
  const files = entries.filter(e => e.type === 'file');
  
  // Sort: dirs first, then files, alphabetical
  const sorted = [
    ...dirs.sort((a, b) => a.name.localeCompare(b.name)),
    ...files.sort((a, b) => a.name.localeCompare(b.name))
  ];
  
  sorted.forEach((entry, index) => {
    const isLast = index === sorted.length - 1;
    const connector = isLast ? '└── ' : '├── ';
    const childPrefix = isLast ? '    ' : '│   ';
    
    if (entry.type === 'directory') {
      tree += `${prefix}${connector}📁 ${entry.name}/\n`;
      if (entry.children && entry.children.length > 0) {
        tree += buildFileTreeInner(entry.children, prefix + childPrefix);
      }
    } else if (entry.type === 'file') {
      const fileIcon = entry.lines > 200 ? '📄' : entry.lines > 50 ? '📝' : '📃';
      tree += `${prefix}${connector}${fileIcon} ${entry.name}`;
      if (entry.lines > 0) {
        tree += ` (${entry.lines} lines${entry.lang !== 'Unknown' ? `, ${entry.lang}` : ''})`;
      }
      tree += '\n';
    }
  });

  return tree;
}

function buildFileTreeInner(entries, prefix) {
  let tree = '';
  const sorted = entries.sort((a, b) => {
    if (a.type !== b.type) return a.type === 'directory' ? -1 : 1;
    return a.name.localeCompare(b.name);
  });
  
  sorted.forEach((entry, index) => {
    const isLast = index === sorted.length - 1;
    const connector = isLast ? '└── ' : '├── ';
    const childPrefix = isLast ? '    ' : '│   ';
    
    if (entry.type === 'directory') {
      tree += `${prefix}${connector}📁 ${entry.name}/\n`;
      if (entry.children && entry.children.length > 0) {
        tree += buildFileTreeInner(entry.children, prefix + childPrefix);
      }
    } else if (entry.type === 'file') {
      tree += `${prefix}${connector}📝 ${entry.name} (${entry.lines} lines)\n`;
    }
  });

  return tree;
}

/**
 * Generate a JSON summary for the web UI.
 */
function generateWebData(project, insights) {
  return {
    projectName: project.projectName,
    projectType: insights.projectType,
    primaryLanguage: insights.primaryLanguage,
    totalFiles: project.totalFiles,
    totalLines: project.totalLines,
    scanTimeMs: project.scanTimeMs,
    scannedAt: project.scannedAt,
    languages: insights.languages,
    modules: insights.modules,
    complexity: insights.complexity,
    architectureDiagram: generateArchitectureDiagram(project, insights),
    topDeclarations: project.declarations.slice(0, 20),
    dependencies: {
      npm: insights.dependencies.packages.slice(0, 15),
      python: insights.dependencies.pythonDeps.slice(0, 15)
    },
    fileTree: buildFileTree(project.entries, project.projectName)
  };
}

module.exports = {
  generateProjectInsights,
  generateArchitectureDiagram,
  generateFullDocs,
  generateWebData
};
